### ISSUE TITLE
Console errors when trying to /sb toggle

### ISSUE THREAD

**Issue by baailey** [joserodpt/RealScoreboard#17]
I am getting errors in console when trying to toggle the scoreboard. Prior to these errors the scoreboard would not toggle at all even though it stated in chat that it has been toggled on/off

```
08.04 04:22:19 [Server] INFO baailey issued server command: /sb reload
08.04 04:22:19 [Server] WARN java.lang.reflect.InvocationTargetException
08.04 04:22:19 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08.04 04:22:19 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08.04 04:22:19 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.04 04:22:19 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
08.04 04:22:19 [Server] WARN at me.mattstudios.mf.base.CommandHandler.executeCommand(CommandHandler.java:232)
08.04 04:22:19 [Server] WARN at me.mattstudios.mf.base.CommandHandler.execute(CommandHandler.java:218)
08.04 04:22:19 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
08.04 04:22:19 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2024)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1835)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1788)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1187)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1180)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1156)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
08.04 04:22:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
08.04 04:22:19 [Server] WARN at java.lang.Thread.run(Thread.java:748)
08.04 04:22:19 [Server] WARN Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
08.04 04:22:19 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537)
08.04 04:22:19 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236)
08.04 04:22:19 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232)
08.04 04:22:19 [Server] WARN at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140)
08.04 04:22:19 [Server] WARN at josegamerpt.realscoreboard.managers.AnimationManager.runLoopers(AnimationManager.java:68)
08.04 04:22:19 [Server] WARN at josegamerpt.realscoreboard.managers.AnimationManager.start(AnimationManager.java:27)
08.04 04:22:19 [Server] WARN at josegamerpt.realscoreboard.managers.AnimationManager.reload(AnimationManager.java:78)
08.04 04:22:19 [Server] WARN at josegamerpt.realscoreboard.RealScoreboard.reload(RealScoreboard.java:125)
08.04 04:22:19 [Server] WARN at josegamerpt.realscoreboard.Commands.reloadCommand(Commands.java:27)
08.04 04:22:19 [Server] WARN ... 25 more
```

**Comment by joserodpt** [comment]
Plugin is disabled. Can you show me your full log?

**Comment by baailey** [comment]
That errors occurs after using PlugMan to reload the plugin, however it still displays as online (green) in /plugins.

I have a different issue that occurs before this error though; for some reason, my players are reporting that /sb toggle will tell them that the scoreboard is being turned on / off even though it doesn't display the scoreboard on their screen. The annoying thing is, it works perfectly fine for me (maybe because I'm OP?). I tried running an /lp verbose to see if maybe there was a hidden permission I was missing, but that was not the case. 

A few days prior when I first put this plugin on, it did work, but overtime it seems to cause issues I don't know how to resolve. I suspect it *could* be the database as I'm simply using localhost information, but I'm not sure. 

Server version: git-Tuinity-"4743c34" (MC: 1.16.4)
Plugin version: 7-4-2021 Build 1
latest log: https://gist.github.com/baailey/717e90ba5b1b0f54329f1e719e8b959b

**Comment by joserodpt** [comment]
Plugman and other reloading plugins are not adviced to be used with any plugin. A restart is the best way of re-loading changes.
In that log there is no error with realscoreboard.
Regarding the issues that you mentioned, it could be tied to that specific console error.
