### ISSUE TITLE
/sb reload error

### ISSUE THREAD

**Issue by baailey** [joserodpt/RealScoreboard#19]
[23:06:27] [Server thread/INFO]: baailey issued server command: /sb reload
[23:06:27] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[23:06:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:06:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:06:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:06:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:06:27] [Server thread/WARN]: 	at me.mattstudios.mf.base.CommandHandler.executeCommand(CommandHandler.java:232)
[23:06:27] [Server thread/WARN]: 	at me.mattstudios.mf.base.CommandHandler.execute(CommandHandler.java:218)
[23:06:27] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:06:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2024)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1835)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1788)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1187)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1180)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1156)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
[23:06:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[23:06:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:06:27] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[23:06:27] [Server thread/WARN]: 	at josegamerpt.realscoreboard.managers.PlayerManager.check(PlayerManager.java:31)
[23:06:27] [Server thread/WARN]: 	at josegamerpt.realscoreboard.RealScoreboard.lambda$reload$3(RealScoreboard.java:120)
[23:06:27] [Server thread/WARN]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[23:06:27] [Server thread/WARN]: 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[23:06:27] [Server thread/WARN]: 	at josegamerpt.realscoreboard.RealScoreboard.reload(RealScoreboard.java:120)
[23:06:27] [Server thread/WARN]: 	at josegamerpt.realscoreboard.Commands.reloadCommand(Commands.java:27)
[23:06:27] [Server thread/WARN]: 	... 25 more

**Comment by joserodpt** [comment]
Please try this build. Thanks!

[RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/6329583/RealScoreboard.zip)

**Comment by baailey** [comment]
The new jar has fixed this issue.
