### ISSUE TITLE
Incompatible with MySQL

### ISSUE THREAD

**Issue by ghost** [joserodpt/RealScoreboard#20]
I've tried connecting to mysql, but it just can't…

```
[22:59:19 INFO]: [RealScoreboard] ------------------- RealScoreboard 11-4-2021 Build 1 -------------------
[22:59:19 ERROR]: Error occurred while enabling RealScoreboard v11-4-2021 Build 1 (Is it up to date?)
java.lang.IllegalArgumentException: Unknown database-type url part 'MYSQL' in: jdbc:MYSQL://212.22.87.7:3306/minecraft
        at com.j256.ormlite.jdbc.db.DatabaseTypeUtils.createDatabaseType(DatabaseTypeUtils.java:55) ~[?:?]
        at josegamerpt.realscoreboard.managers.DatabaseManager.<init>(DatabaseManager.java:37) ~[?:?]
        at josegamerpt.realscoreboard.RealScoreboard.onEnable(RealScoreboard.java:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:949) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.Bukkit.reload(Bukkit.java:726) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-599]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-599]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452) ~[patched_1.16.5.jar:git-Paper-599]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-599]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-599]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-599]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-599]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[22:59:19 INFO]: [RealScoreboard] Disabling RealScoreboard v11-4-2021 Build 1
```

**Comment by joserodpt** [comment]
Hi there. Please check if the new update works.
If not, message me on Discord. Thanks!
