### ISSUE TITLE
LuckPerms reported issue

### ISSUE THREAD

**Issue by UltimaOath** [joserodpt/RealScoreboard#21]
Hello!
While I do not use your plugin, a user on our support discord for an unrelated plugin reported this issue and I thought I'd send the report your way.

https://pastebin.com/KNu1Gbwb

The 'meat' of the report:
```
[13:51:18] [Server thread/WARN]: This is NOT a bug - please do not report it to LuckPerms.
[13:51:18] [Server thread/WARN]: Instead, please carefully read the information given below.
[13:51:18] [Server thread/WARN]: 
[13:51:18] [Server thread/WARN]: LuckPerms cannot respond to the request because to do so:
[13:51:18] [Server thread/WARN]: - it needs to lookup user data for 'a3156699-af6c-38f7-9403-a4911afbb143' (an offline player) from the database
[13:51:18] [Server thread/WARN]: 
[13:51:18] [Server thread/WARN]: Performing this lookup on the main server thread would cause your server to lag.
[13:51:18] [Server thread/WARN]: There are two solutions to this problem:
[13:51:18] [Server thread/WARN]:   a) Ask the author of the plugin making the request to perform Vault calls for
[13:51:18] [Server thread/WARN]:      offline players "asynchronously" (using the scheduler). Additionally, prefer
[13:51:18] [Server thread/WARN]:      using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
[13:51:18] [Server thread/WARN]:      You should be able to identify the plugin making the request in the trace below.
[13:51:18] [Server thread/WARN]:   b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
[13:51:18] [Server thread/WARN]:      to true in the LuckPerms configuration file. However, please use this only as
[13:51:18] [Server thread/WARN]:      a last resort.
```
```
[13:51:18] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:154)
[13:51:18] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetPrimaryGroup(LuckPermsVaultPermission.java:249)
[13:51:18] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPrimaryGroup(AbstractVaultPermission.java:385)
[13:51:18] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.vault.AbstractVaultChat.getPrimaryGroup(AbstractVaultChat.java:683)
[13:51:18] [Server thread/WARN]: 	at josegamerpt.realscoreboard.utils.Placeholders.prefix(Placeholders.java:101)
[13:51:18] [Server thread/WARN]: 	at josegamerpt.realscoreboard.utils.Placeholders.setPlaceHolders(Placeholders.java:169)
[13:51:18] [Server thread/WARN]: 	at josegamerpt.realscoreboard.SBPlayer$1.run(SBPlayer.java:71)
[13:51:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:51:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
[13:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:430)
[13:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1403)
[13:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
[13:51:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:51:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by joserodpt** [comment]
Thats weird. May i ask what the version of the plugin is?

**Comment by UltimaOath** [comment]
Sorry for delay, the user who reported had to get back to me. 

Server: Purpur-1051 (MC: 1.16.5)
RealScoreboard: v28-2-2021 Build 1

I have informed player about outdated server build to update and see if that resolves.

**Comment by joserodpt** [comment]
That was fixed in https://github.com/JoseGamerPT/RealScoreboard/commit/4aafc15996faa62d26eb434de921ed992a1eecf7

**Comment by UltimaOath** [comment]
Sorry for the outdated report! The user came to our support server and had troubles so just wanted to help where I could. Sorry again for the inconvenience.

**Comment by joserodpt** [comment]
No problem!
