### ISSUE TITLE
No longer working on Paper 1.19.2

### ISSUE THREAD

**Issue by JimDude7404** [joserodpt/RealScoreboard#43]
RealScoreboard no longer works after the latest paper update, its red in my plugins.

**Comment by neziw** [comment]
Please send logs.

**Comment by JimDude7404** [comment]
[00:14:18 INFO]: [RealScoreboard] Enabling RealScoreboard v12-08-2022 Build 1
[00:14:18 INFO]: [RealScoreboard] ------------------- RealScoreboard 12-08-2022 Build 1 -------------------
[00:14:18 ERROR]: Cannot load plugins/RealScoreboard/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 24, column 5:
        world:
        ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 26, column 7:
          default:
          ^
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:105) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:305) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at josegamerpt.realscoreboard.config.Config.setup(Config.java:31) ~[RealScoreboard.jar:?]
        at josegamerpt.realscoreboard.RealScoreboard.onEnable(RealScoreboard.java:57) ~[RealScoreboard.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-191]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-191]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-191]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 24, column 5:
        world:
        ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 26, column 7:
          default:
          ^
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:679) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:210) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[snakeyaml-1.33.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 16 more
[00:14:19 INFO]: [RealScoreboard] Your config version is: 1
[00:14:19 INFO]: [RealScoreboard] Failed to load RealScoreboard.
[00:14:19 INFO]: [RealScoreboard] There are some problems with your config: Missing Disabled-Worlds Section on config.yml | Please look at the original config.yml, Missing Bypassed-Worlds Section on config.yml | Please look at the original config.yml
Please check this errors. Plugin is disabled due to config errors.
[00:14:19 INFO]: [RealScoreboard] If you think this is a bug, please contact JoseGamer_PT.
[00:14:19 INFO]: [RealScoreboard] https://www.spigotmc.org/members/josegamer_pt.40267/
[00:14:19 INFO]: [RealScoreboard] ------------------- RealScoreboard 12-08-2022 Build 1 -------------------
[00:14:19 INFO]: [RealScoreboard] Disabling RealScoreboard v12-08-2022 Build 1

**Comment by JimDude7404** [comment]
oh nvm imma close this, after pasting this i realized what my mistake is...

**Comment by JimDude7404** [comment]
My config is

Debug: false
Config:
  Check-for-Updates: true
  Prefix: '&bReal&9Scoreboard &7| &r'
  Reloaded: '&fThe config has been &areloaded&f.'
  Use-Placeholders-In-Scoreboard-Titles: false
  RealScoreboard-Disabled-By-Default: false
  Hours:
    Formatting: 'HH:mm:ss'
    Offset: 0
  Messages:
    Scoreboard-Toggle:
      'ON': '&fScoreboard turned &aON&f.'
      'OFF': '&fScoreboard turned &cOFF&f.'
  Animations:
    Title-Delay: 20
    Loop-Delay: 20
  Scoreboard-Refresh: 10
  Disabled-Worlds:
    - testWorld
    - ExampleWorld2
  Bypass-Worlds:
    - skywarsLobby
  Scoreboard:
    world:
    - world
      default:
        Switch-Timer: 35
        Boards:
          Board1:
            Title:
              - '&d&lAlanium&5&lMC'
            Lines:
              - ''
              - ' &5%player_name%'
              - ' &7Rank: %luckperms_primary_group_name%'
              - ''
              - '&5&l│ &7Balance: &2$&a%vault_eco_balance_formatted%'
              - '&5&l│ &7Playtime: &a%statistic_time_played%'
              - '&5&l│ &7Season: &a4'
              - ''
              - '&dalanium.net'
Version: 12

**Comment by JimDude7404** [comment]
and its showing that its wrong config when its not

**Comment by joserodpt** [comment]
The error is here, check it.

Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 24, column 5:
world:
^
expected , but found ''
in 'reader', line 26, column 7:
default:
^
