### ISSUE TITLE
DeluxeMenu Error

### ISSUE THREAD

**Issue by Unipotatoo** [joserodpt/RealScoreboard#53]
Hello, Ive been using the 'realscoreboard' plugin for a while and when I updated it recently, I can no longer open my settings menu(deluxemenus). I have a toggleable option for the sidebar and normally when the menu acts up it happens because of an outdated papi extension. I've tried what I could think of and I can't get it to work, was wondering if you could understand this error message relating to realscoreboard.
`[16:51:10 INFO]: Unipotatoo issued server command: /settings
[16:51:10 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.13.6-Release generated an exception while executing task 111039
java.lang.ClassCastException: class josegamerpt.realscoreboard.RealScoreboardPlugin cannot be cast to class josegamerpt.realscoreboard.RealScoreboard (josegamerpt.realscoreboard.RealScoreboardPlugin and josegamerpt.realscoreboard.RealScoreboard are in unnamed module of loader 'RealScoreboard-Plugin-18-11-2022 Build 1.jar' @8d02279)
        at Expansion.onRequest(Expansion.java:108) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.2.jar:?]
        at com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(MenuHolder.java:95) ~[DeluxeMenus-1.13.6-Release.jar:?]
        at com.extendedclip.deluxemenus.requirement.InputResultRequirement.evaluate(InputResultRequirement.java:21) ~[DeluxeMenus-1.13.6-Release.jar:?]
        at com.extendedclip.deluxemenus.requirement.RequirementList.evaluate(RequirementList.java:21) ~[DeluxeMenus-1.13.6-Release.jar:?]
        at com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$5(Menu.java:374) ~[DeluxeMenus-1.13.6-Release.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-119]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by neziw** [comment]
@Unipotatoo can you show list of your installed expansions?

**Comment by Unipotatoo** [comment]
https://cdn.discordapp.com/attachments/817811422117101609/1051926758355636284/image.png

**Comment by neziw** [comment]
This problem is caused by custom expansion which author of issue uses. Main plugin class was renamed from RealScoreboard to RealScoreboardPlugin in API update due to Java limits (I can't extend two classes in the same time, you can understand this by reading my Pull Request which adds API).

Solution is one - just update expansion 😀
