### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by ghost** [joserodpt/RealScoreboard#57]
Paste - https://paste.walshy.dev/QxpFSR89tqzs

```[07:01:36 WARN]: java.sql.SQLException: Could not create object for class josegamerpt.realscoreboard.api.config.PlayerData
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.dao.BaseDaoImpl.createObjectInstance(BaseDaoImpl.java:1010)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:54)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:290)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:163)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:207)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:127)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:251)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//josegamerpt.realscoreboard.managers.DatabaseManager.getPlayerData(DatabaseManager.java:75)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//josegamerpt.realscoreboard.managers.DatabaseManager.<init>(DatabaseManager.java:50)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//josegamerpt.realscoreboard.RealScoreboardPlugin.onEnable(RealScoreboardPlugin.java:86)
[07:01:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:01:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:01:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[07:01:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[07:01:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[07:01:36 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[07:01:36 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[07:01:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[07:01:36 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[07:01:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[07:01:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:01:36 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[07:01:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:01:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[07:01:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:01:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[07:01:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//com.j256.ormlite.dao.BaseDaoImpl.createObjectInstance(BaseDaoImpl.java:1003)
[07:01:36 WARN]:        ... 20 more
[07:01:36 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "josegamerpt.realscoreboard.api.RealScoreboardAPI.getPlayerManager()" because the return value of "josegamerpt.realscoreboard.api.RealScoreboardAPI.getInstance()" is null
[07:01:36 WARN]:        at RealScoreboard-Plugin-18-11-2022 Build 1.jar//josegamerpt.realscoreboard.api.config.PlayerData.<init>(PlayerData.java:21)
[07:01:36 WARN]:        ... 26 more```

**Comment by joserodpt** [comment]
Fixed in the new update.
