### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by JuusK** [joserodpt/RealScoreboard#61]
SOMEONE PLS HELP ME THIS IS GETTING SPAMMED AND I DONT KNOW WHATS CAUSING IT
**_[09:44:05 ERROR]: [RealScoreboard] [ERROR] RealScoreboard threw an error while trying to display the scoreboard for JuusK
[09:44:05 WARN]: java.lang.NullPointerException: Cannot invoke "me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()" because the return value of "me.clip.placeholderapi.PlaceholderAPIPlugin.getInstance()" is null
[09:44:05 WARN]:        at BagelSMP.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:72)
[09:44:05 WARN]:        at BagelSMP.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[09:44:05 WARN]:        at realscoreboard-plugin-1.0 (2).jar//josegamerpt.realscoreboard.utils.Placeholders.placeholderAPI(Placeholders.java:203)
[09:44:05 WARN]:        at realscoreboard-plugin-1.0 (2).jar//josegamerpt.realscoreboard.utils.Placeholders.setPlaceHolders(Placeholders.java:198)
[09:44:05 WARN]:        at realscoreboard-plugin-1.0 (2).jar//josegamerpt.realscoreboard.api.scoreboard.ScoreboardTask.lambda$run$0(ScoreboardTask.java:48)
[09:44:05 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[09:44:05 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[09:44:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[09:44:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[09:44:05 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[09:44:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09:44:05 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[09:44:05 WARN]:        at realscoreboard-plugin-1.0 (2).jar//josegamerpt.realscoreboard.api.scoreboard.ScoreboardTask.run(ScoreboardTask.java:50)
[09:44:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[09:44:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[09:44:05 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:44:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:44:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:44:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)_**

**Comment by joserodpt** [comment]
You are having a problem with PlaceholderAPI detection
