### ISSUE TITLE
Could not pass event PlayerQuitEvent to RealScoreboard

### ISSUE THREAD

**Issue by ruk13xa** [joserodpt/RealScoreboard#77]
2|kr_smp  | [20:55:10 ERROR]: Could not pass event PlayerQuitEvent to RealScoreboard v1.4.3
2|kr_smp  | java.lang.NullPointerException: Cannot invoke "joserodpt.realscoreboard.api.scoreboard.RSBPlayer.stopScoreboard()" because the return value of "joserodpt.realscoreboard.api.managers.AbstractPlayerManager.getPlayer(java.util.UUID)" is null
2|kr_smp  |     at RealScoreboard.jar/joserodpt.realscoreboard.listeners.PlayerListener.leave(PlayerListener.java:35) ~[RealScoreboard.jar:?]
2|kr_smp  |     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor590.execute(Unknown Source) ~[?:?]
2|kr_smp  |     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at net.minecraft.server.players.PlayerList.remove(PlayerList.java:607) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2115) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2095) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect0(ServerCommonPacketListenerImpl.java:426) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:417) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:374) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.craftbukkit.entity.CraftPlayer.kickPlayer(CraftPlayer.java:660) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.events.CacheListener.onJoin(CacheListener.java:22) ~[DiscordUtils.jar:?]
2|kr_smp  |     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor568.execute(Unknown Source) ~[?:?]
2|kr_smp  |     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
2|kr_smp  |     at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ruk13xa** [comment]
it emits this error and keeps kicking player
with this message
"lost connection: The server is still loading, please, wait a bit and try joining again."

**Comment by ruk13xa** [comment]
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/d5fa6c41-874e-4b31-8acc-b9d4f6c9278f">

**Comment by ruk13xa** [comment]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/d2a1b67a-035b-4b06-92da-92e368b1dd3a">

**Comment by ruk13xa** [comment]
I found out that it was a problem with bluemap
